name: environment
channels:
    - pytorch
    - defaults
dependencies:
    - python
    - tqdm
    - tensorboard
    - numpy
    - scipy
    - matplotlib
    - seaborn
    - scikit-learn
    - pip:
        - ipykernel==6.28.0
        - ipython==8.12.3
        - torch==1.10.2+cu113
        - torchaudio==0.10.2+cu113
        - torchvision==0.11.3+cu113

# torch==1.10.2+cu113
# torchvision==0.11.3+cu113
# torchaudio==0.10.2+cu113